- name: Home
  columns:
    - size: small
      - type: videos
        channels:
          - UCrDwWp7EBBv4NwvScIpBDOA # Anthropic
    - size: small
      - type: videos
        channels:
          - UCrDwWp7EBBv4NwvScIpBDOA # Anthropic
    - size: small
      - type: videos
        channels:
          - UCrDwWp7EBBv4NwvScIpBDOA # Anthropic
