- name: Home
  columns:
    - size: small
      widgets:
        - type: videos
          channels:
            - UCrDwWp7EBBv4NwvScIpBDOA # Anthropic
    - size: small
      widgets:
        - type: videos
          channels:
            - UCrDwWp7EBBv4NwvScIpBDOA # Anthropic
    - size: small
      widgets:
        - type: videos
          channels:
            - UCrDwWp7EBBv4NwvScIpBDOA # Anthropic
