- name: Gaming
  columns:
    - size: small
      widgets:
        - type: twitch-top-games
          limit: 20
          collapse-after: 13
          exclude:
            - just-chatting
            - pools-hot-tubs-and-beaches
            - music
            - art
            - asmr

    - size: full
      widgets:
        - type: group
          define: &shared-properties
            type: reddit
            show-thumbnails: true
            collapse-after: 6
            limit: 7
            style: vertical-cards
            app-auth:
              name: ${REDDIT_APP_NAME}
              id: ${REDDIT_APP_CLIENT_ID}
              secret: ${REDDIT_APP_SECRET}
          widgets:
            - subreddit: pcgaming
              <<: *shared-properties
            - subreddit: games
              <<: *shared-properties
            - subreddit: gamingnews
              <<: *shared-properties

        - type: videos
          style: grid-cards
          collapse-after-rows: 3
          channels:
            - UCNvzD7Z-g64bPXxGzaQaa4g # gameranx
            - UCZ7AeeVbyslLM_8-nVy2B8Q # Skill Up
            - UCHDxYLv8iovIbhrfl16CNyg # GameLinked
            - UC9PBzalIcEQCsiIkq36PyUA # Digital Foundry

    - size: small
      widgets:
        - type: custom-api
          title: Steam Specials
          cache: 12h
          url: https://store.steampowered.com/api/featuredcategories?cc=us
          template: |
            <ul class="list list-gap-10 collapsible-container" data-collapse-after="5">
            {{ range .JSON.Array "specials.items" }}
              <li>
                <a class="size-h4 color-highlight block text-truncate" href="https://store.steampowered.com/app/{{ .Int "id" }}/">{{ .String "name" }}</a>
                <ul class="list-horizontal-text">
                  <li>{{ div (.Int "final_price" | toFloat) 100 | printf "$%.2f" }}</li>
                  {{ $discount := .Int "discount_percent" }}
                  <li{{ if ge $discount 40 }} class="color-positive"{{ end }}>{{ $discount }}% off</li>
                </ul>
              </li>
            {{ end }}
            </ul>

  branding:
    custom-footer: |
      <p>Powered by <a href="https://github.com/glanceapp/glance">Glance</a></p>
    # logo-url: /assets/logo.png
    # favicon-url: /assets/logo.png
    app-name: "My Dashboard"
    # app-icon-url: "/assets/app-icon.png"
    # app-background-color: "#151519"