- name: Home
  columns:
    - size: small
      widgets:
        - type: calendar
          first-day-of-week: monday

        - type: rss
          limit: 10
          collapse-after: 3
          cache: 12h
          feeds:
            - url: https://selfh.st/rss/
              title: selfh.st
              limit: 4
            - url: https://ciechanow.ski/atom.xml
            - url: https://www.joshwcomeau.com/rss.xml
              title: Josh Comeau
            - url: https://samwho.dev/rss.xml
            - url: https://ishadeed.com/feed.xml
              title: Ahmad Shadeed


    - size: full
      widgets:
        - type: group
          widgets:
            - type: hacker-news
            - type: lobsters

        - type: videos
          channels:
            - UCXuqSBlHAE6Xw-yeJA0Tunw # Linus Tech Tips
            - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
            - UCsBjURrPoezykLs9EqgamOA # Fireship
            - UCBJycsmduvYEL83R_U4JriQ # Marques Brownlee
            - UCHnyfMqiRRG1u-2MsSQLbXA # Veritasium
            - UCMUnInmOkrWN4gof9KlhNmQ # 老高與小茉

        - type: group
          define: &shared-properties
            type: reddit
            show-thumbnails: true
            collapse-after: 6
            app-auth:
              name: ${REDDIT_APP_NAME}
              id: ${REDDIT_APP_CLIENT_ID}
              secret: ${REDDIT_APP_SECRET}
          widgets:
            - subreddit: technology
              <<: *shared-properties
            - subreddit: selfhosted
              <<: *shared-properties

    - size: small
      widgets:
        - type: weather
          location: Guangzhou, China
          units: metric # alternatively "imperial"
          hour-format: 24h # alternatively "24h"
          # Optionally hide the location from being displayed in the widget
          # hide-location: true

        - type: clock
          hide-header: true
          hour-format: 24h
          timezones:
            - timezone: Europe/Paris
              label: 巴黎
            - timezone: America/New_York
              label: 纽约
            - timezone: America/Sao_Paulo
              label: 圣保罗

        - type: releases
          cache: 1d
          # Without authentication the Github API allows for up to 60 requests per hour. You can create a
          # read-only token from your Github account settings and use it here to increase the limit.
          # token: ...
          repositories:
            - glanceapp/glance
            - Dokploy/dokploy
            - dgtlmoon/changedetection.io
            - home-assistant/core
            - immich-app/immich
            - syncthing/syncthing

        # - type: rss
        #   limit: 10
        #   collapse-after: 3
        #   cache: 12h
        #   feeds:
        #     - url: https://www.lennysnewsletter.com/sitemap.xml
        #       title: Lennys Newsletter
        #       limit: 10